twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  paths:
    '%kernel.project_dir%/assets/css': 'styles'
    '%kernel.project_dir%/assets/images': 'images'
    '%kernel.project_dir%/templates': 'TFMHolidaysManagement'
  globals:
    app_name: '%app.name%'
    app_vendor_name: '%app.vendor.name%'
    app_support_email: '%app.support.email%'
    app_documents_directory: '%app.documents.directory%'
