TFM\HolidaysManagement\Country\Domain\Model\Aggregate\Country:
  type: entity
  table: country
  id:
    id:
      column: uuid
      type: uuid
  fields:
    name:
      column: name
      type: string
      length: 50
      nullable: false
      unique: true
    createdOn:
      column: created_on
      type: datetime_immutable
      nullable: false
    updatedOn:
      column: updated_on
      type: datetime_immutable
      nullable: true
  oneToMany:
    regions:
      targetEntity: TFM\HolidaysManagement\Country\Domain\Model\Aggregate\Region\Region
      mappedBy: countries
      fetch: EXTRA_LAZY