TFM\HolidaysManagement\Country\Domain\Model\Aggregate\Region\Town\Town:
  type: entity
  table: country_region_town
  id:
    id:
      column: uuid
      type: uuid
  fields:
    name:
      column: name
      type: string
      length: 50
      nullable: false
      unique: true
    createdOn:
      column: created_on
      type: datetime_immutable
      nullable: false
    updatedOn:
      column: updated_on
      type: datetime_immutable
      nullable: true
  manyToOne:
    regions:
      targetEntity: TFM\HolidaysManagement\Country\Domain\Model\Aggregate\Region\Region
      inversedBy: towns
      joinColumn:
        name: region_id
        referencedColumnName: uuid
  manyToMany:
    postalCodes:
      targetEntity: TFM\HolidaysManagement\Country\Domain\Model\Aggregate\Region\PostalCode\PostalCode
      inversedBy: towns
      orderBy: { 'value': 'ASC' }
      joinTable:
          name: town_postal_codes
          joinColumns:
            town_id:
              referencedColumnName: uuid
          inverseJoinColumns:
            postal_code_id:
              referencedColumnName: uuid

